<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Apply</name>
   <tag></tag>
   <elementGuidId>bb8e65ae-2fb5-4aac-b737-40252ebc0949</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[9]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.daterangepicker.ltr.show-calendar.opensright > div.drp-buttons > button.applyBtn.btn.btn-sm.btn-primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d57c4e1e-38b4-49c9-ade2-3945a9eae0bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>applyBtn btn btn-sm btn-primary</value>
      <webElementGuid>b77be635-1468-43b3-8fc6-7045db007cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>697cef67-43d6-43a1-9e9e-325818bb4dae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apply</value>
      <webElementGuid>7cf29e3d-0099-4a45-b726-7d6f23f52041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;skin-firefly-iii sidebar-mini&quot;]/div[@class=&quot;daterangepicker ltr show-calendar opensright&quot;]/div[@class=&quot;drp-buttons&quot;]/button[@class=&quot;applyBtn btn btn-sm btn-primary&quot;]</value>
      <webElementGuid>9bf02c60-fd2e-4f3c-82c9-e930dec28893</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[9]</value>
      <webElementGuid>488a597f-14bd-4e6d-a074-da219556843b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[4]/button[2]</value>
      <webElementGuid>1fdc26ee-7cdb-42c7-adf4-c0391b6ebc47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Apply' or . = 'Apply')]</value>
      <webElementGuid>6f4b958e-91dd-4f0a-adf8-79dc4d8472ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
