<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span</name>
   <tag></tag>
   <elementGuidId>54f19542-14d2-4a66-8d69-2990cd97eba0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//th/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>th.prev.available > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b2854a68-64d7-4adf-b9ed-1909c9a4e639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;skin-firefly-iii sidebar-mini&quot;]/div[@class=&quot;daterangepicker ltr show-calendar opensright&quot;]/div[@class=&quot;drp-calendar left&quot;]/div[@class=&quot;calendar-table&quot;]/table[@class=&quot;table-condensed&quot;]/thead[1]/tr[1]/th[@class=&quot;prev available&quot;]/span[1]</value>
      <webElementGuid>14c8baa7-c706-4644-9f88-4f359eb0eb5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th/span</value>
      <webElementGuid>bb4de613-377d-490f-8751-54c1baffa8f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
