<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Euro ()British Pound ()Hungarian for_48a2bd</name>
   <tag></tag>
   <elementGuidId>853ad8fd-375d-427e-b65d-140f219430f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ffInput_transaction_currency_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ffInput_transaction_currency_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6fdd1406-8411-4006-994c-ffe16237e8da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0a11ab87-5a79-4a7b-b37c-57a4d5dd337d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>transaction_currency_id</value>
      <webElementGuid>bb000409-cad9-4482-8b49-86dda57023d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_transaction_currency_id</value>
      <webElementGuid>78a76839-5197-49d1-9067-135f021a958d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c4d603ea-843e-4817-884e-33452aa48ac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bc06be52-bc61-40b7-8d70-eaa3cafc71a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Euro (€)British Pound (£)Hungarian forint (Ft)US Dollar ($)</value>
      <webElementGuid>861c9a7e-ab2f-4618-a28e-3b7c86a64bfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_transaction_currency_id&quot;)</value>
      <webElementGuid>b55b4e6e-382a-41ee-a8e4-75ce95f28307</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ffInput_transaction_currency_id']</value>
      <webElementGuid>7b6a8ff9-722a-4fcf-91d8-c1c0c9f6cf55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='transaction_currency_id_holder']/div/select</value>
      <webElementGuid>c109c98b-8414-440e-acf3-25ec49eaee53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>883b93b7-c883-4e6c-9181-446bf9d44f2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'transaction_currency_id' and @id = 'ffInput_transaction_currency_id' and (text() = 'Euro (€)British Pound (£)Hungarian forint (Ft)US Dollar ($)' or . = 'Euro (€)British Pound (£)Hungarian forint (Ft)US Dollar ($)')]</value>
      <webElementGuid>d5c7b9ad-14a3-4bdc-b4c1-57c7d4478c4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
