<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_dailyweeklymonthlyquarterlyevery hal_79c7c6</name>
   <tag></tag>
   <elementGuidId>ae14590a-b052-452a-9e0b-2ac4bc927bc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ffInput_repeat_freq']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ffInput_repeat_freq</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8cf7b77c-6b55-430d-b3c8-b92abcb5aaea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>53c99221-7f41-40b0-b409-347d6d5a85a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>repeat_freq</value>
      <webElementGuid>10549cbc-5c2f-48cf-bab2-f5dfc35d89a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_repeat_freq</value>
      <webElementGuid>09c82697-9b71-4980-b0aa-1cbb66da521d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0282b945-21b7-4dee-8687-326684bb65e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>15aecd57-2752-44c0-9f67-47a502f47395</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>dailyweeklymonthlyquarterlyevery half-yearyearly</value>
      <webElementGuid>9c967b64-0a13-45e2-b5b4-aa3dcc3bd03e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_repeat_freq&quot;)</value>
      <webElementGuid>477c2e73-13a4-4e1b-83b2-7fb2dda24135</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ffInput_repeat_freq']</value>
      <webElementGuid>3aef579e-3b9f-441f-8f1d-add9f8aa4bd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='repeat_freq_holder']/div/select</value>
      <webElementGuid>625ee6b9-43ad-40e6-93b0-01029151d86a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/select</value>
      <webElementGuid>f63851d2-cb3a-4d63-a2cf-35493d8926d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'repeat_freq' and @id = 'ffInput_repeat_freq' and (text() = 'dailyweeklymonthlyquarterlyevery half-yearyearly' or . = 'dailyweeklymonthlyquarterlyevery half-yearyearly')]</value>
      <webElementGuid>7000eda0-ca24-4c92-b6e2-6707a1870043</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
